name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed for pushing to the output branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (full history)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Generate the snake SVG
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ShaikAbdulHafeez474
          outputs: dist/snake.svg

      # Push the generated snake.svg to 'output' branch
      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
